name: 'OpenJDK Mobile Static Release'

on: workflow_dispatch

jobs:
  build-android-linux-aarch64:
    name: android-linux-aarch64
    uses: ./.github/workflows/build-android-static.yml
    with:
      platform: linux-x64
      gcc-major-version: '10'

  build-ios-macos-aarch64:
    name: ios-macos-aarch64
    uses: ./.github/workflows/build-ios-static.yml
    with:
      platform: macos-aarch64
      runs-on: 'macos-14'
      xcode-toolset-version: '14.3.1'

  early-access:
    needs: [ build-android-linux-aarch64, build-ios-macos-aarch64 ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v2
      - name: Check downloads
        run: ls
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
